version: "3.3"

services:
  jenkins-docker:
    build:
      context: .
      dockerfile: jenkins-docker.dockerfile
      args:
        # ホストの環境変数をビルド時の引数 (ARG) として受け取る
        https_proxy: ${https_proxy}
    image: myjenkins-docker
    container_name: jenkins-docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    volumes:
      - ${VOLUME_ROOT}/docker-certs:/certs/client
      - ${VOLUME_ROOT}/jenkins_home:/var/jenkins_home
    ports:
      - "2376:2376"
    networks:
      - jenkins
      - jenkins-external
    # docker:dind の引数。Linux環境でストレージ効率を最適化するためのオプション。
    command: --storage-driver overlay2

  jenkins-blueocean:
    build:
      context: .
      args:
        # ホストの環境変数をビルド時の引数 (ARG) として受け取る
        JENKINS_VERSION: $JENKINS_VERSION
        PROXY: $PROXY
        NO_PROXY: $NO_PROXY
        HOST_UID: $HOST_UID
        HOST_GID: $HOST_GID
    image: myjenkins-blueocean:${JENKINS_VERSION}-1
    container_name: jenkins-blueocean
    restart: on-failure
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - ftp_proxy=${ftp_proxy}
      - all_proxy=${all_proxy}
      - no_proxy=${no_proxy}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - FTP_PROXY=${FTP_PROXY}
      - ALL_PROXY=${ALL_PROXY}
      - NO_PROXY=${NO_PROXY}
      - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS}
      # - JENKINS_URL=${JENKINS_URL}
      # export HOST_UID=$(id -u)
      # export HOST_GID=$(id -g)
      - HOST_UID
      - HOST_GID
    # user: "1012:1000"
    # user: "${HOST_UID}:${HOST_GID}"
    volumes:
      - ./etc/environment:/etc/environment
      - ./usr/local/share/ca-certificates/:/usr/local/share/ca-certificates/
      - ${VOLUME_ROOT}/docker-certs/:/certs/client:ro
      - ${VOLUME_ROOT}/java-certs/:/opt/java/openjdk/lib/security/
      - ${VOLUME_ROOT}/jenkins_home/:/var/jenkins_home/
    secrets:
      - jenkins-secret
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
      - jenkins-external
    links:
      - jenkins-docker:docker

secrets:
  jenkins-secret:
    file: run/secrets/jenkins-secret

networks:
  jenkins:
  # docker network create --subnet 10.6.80.0/24 jenkins-external
  jenkins-external:
    external: true
