version: "3.3"

services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    volumes:
      - ${VOLUME_ROOT}/docker-certs:/certs/client
      - ${VOLUME_ROOT}/jenkins_home:/var/jenkins_home
    ports:
      - "2376:2376"
    networks:
      - jenkins
    # docker:dind の引数。Linux環境でストレージ効率を最適化するためのオプション。
    command: --storage-driver overlay2

  jenkins-blueocean:
    build:
      context: .
      args:
        # ホストの環境変数をビルド時の引数 (ARG) として受け取る
        JENKINS_VERSION: $JENKINS_VERSION
        PROXY: $PROXY
        NO_PROXY: $NO_PROXY
    image: myjenkins-blueocean:${JENKINS_VERSION}-1
    container_name: jenkins-blueocean
    restart: on-failure
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - ftp_proxy=${ftp_proxy}
      - all_proxy=${all_proxy}
      - no_proxy=${no_proxy}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - FTP_PROXY=${FTP_PROXY}
      - ALL_PROXY=${ALL_PROXY}
      - NO_PROXY=${NO_PROXY}
      - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS}
      # - JENKINS_URL=${JENKINS_URL}
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./etc/environment:/etc/environment
      - ./usr/local/share/ca-certificates/:/usr/local/share/ca-certificates/
      - ${VOLUME_ROOT}/docker-certs/:/certs/client:ro
      - ${VOLUME_ROOT}/java-certs/:/opt/java/openjdk/lib/security/
      - ${VOLUME_ROOT}/jenkins_home/:/var/jenkins_home/
    secrets:
      - jenkins-secret
    networks:
      - jenkins

networks:
  jenkins:

secrets:
  jenkins-secret:
    file: run/secrets/jenkins-secret
