version: "3.9"

services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - http_proxy
      - https_proxy
      - no_proxy
    volumes:
      - /Users/Shared/.local/share/jenkins-docker-certs:/certs/client
      - /Users/Shared/.local/share/jenkins-data:/var/jenkins_home
      - /Users/Shared/.local/share/proxy-certs:/usr/local/share/ca-certificates/proxy-certs
    ports:
      - "2376:2376"
    networks:
      - jenkins
    command: --storage-driver overlay2

  jenkins-blueocean:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: myjenkins-blueocean:2.387.2-1
    container_name: jenkins-blueocean
    restart: on-failure
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - http_proxy
      - https_proxy
      - no_proxy
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /Users/Shared/.local/share/jenkins-data:/var/jenkins_home
      - /Users/Shared/.local/share/jenkins-docker-certs:/certs/client:ro
      - /Users/Shared/.local/share/proxy-certs:/usr/local/share/ca-certificates/proxy-certs
    networks:
      - jenkins

networks:
  jenkins:
    external: true
